spring:
  application:
    name: Gateway-I-Care

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials RETAIN_UNIQUE
      server:
        webflux:
          routes:
            - id: user-service
              uri: ${USER_SERVICE_PATH:http://localhost:8081}
              predicates:
                - Path=/auth/**
            - id: profile-service
              uri: ${PROFILE_SERVICE_PATH:http://localhost:8082}
              predicates:
                - Path=/profile/**
            - id: pharmacy-service
              uri: ${PHARMACY_SERVICE_PATH:http://localhost:8083}
              predicates:
                - Path=/pharmacy/**
            - id: media-service
              uri: ${MEDIA_SERVICE_PATH:http://localhost:8089}
              predicates:
                - Path=/media/**
            - id: appointment-service
              uri: ${APPOINTMENT_SERVICE_PATH:http://localhost:8086}
              predicates:
                - Path=/appointment/**
            - id: notification-service
              uri : ${NOTIFICATION_SERVICE_PATH:http://localhost:8085}
              predicates:
                - Path=/api/mail/**

server:
  port: ${SERVER_PORT:8080}

secret:
  header:
    key: ${SECRET_HEADER_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret:
    key: ${JWT_SECRET_KEY }